### ISSUE TITLE
Admin UI: Switching page to referenced model (temporary) breaks app

### ISSUE THREAD

**Issue by fabianbru** [keystonejs/keystone-classic#3696]
### Steps to reproduce the behavior

Keystone version: 4.0.0-beta.3

1. Open detail view of one item of model referenced somewhere else (e.g.: "ExampleAuthor" of "Author")
2. Navigate to list view with referenced model used as defaultColumns (e.g.: "Post" model with "Author" model as defaultColumn)
3. Click on one of the referenced items (e.g.: "OtherExampleAuthor" of "Author")

### Expected behavior
Opens detail view of model.

### Actual behavior
Opens detail view of item from list view with the name field from the last viewed referenced model (in the example above: Clicking on "OtherExampleAuthor" in list view opens a "Post" model with an name field of "ExampleAuthor" -> all is mixed up) and outputs JS error in console:
```
fields.js:9421 Uncaught TypeError: values.split is not a function
    at t.loadValue (https://XYZ/keystone/js/fields.js:9421:52)
    at t.componentDidMount (https://XYZ/keystone/js/fields.js:9362:8)
    at r.notifyAll (https://XYZ/keystone/js/packages.js:2759:33)
    at r.close (https://XYZ/keystone/js/packages.js:3605:157)
    at r.closeAll (https://XYZ/keystone/js/packages.js:3795:49)
    at r.perform (https://XYZ/keystone/js/packages.js:3792:144)
    at o.perform (https://XYZ/keystone/js/packages.js:3792:61)
    at o.perform (https://XYZ/keystone/js/packages.js:3686:318)
    at Object.O [as flushBatchedUpdates] (https://XYZ/keystone/js/packages.js:3688:3)
    at r.closeAll (https://XYZ/keystone/js/packages.js:3795:49)
```
Also all field values are gone/empty.

In this state if I click on another menu item in top navigation, then nothing happens except a JS error in console:
```
fields.js:3360 Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
    at t.componentWillUnmount (https://XYZ/keystone/js/fields.js:3360:17)
    at p.unmountComponent (https://XYZ/keystone/js/packages.js:3087:66)
    at Object.unmountComponent (https://XYZ/keystone/js/packages.js:3608:210)
    at p.unmountComponent (https://XYZ/keystone/js/packages.js:3088:29)
    at Object.unmountComponent (https://XYZ/keystone/js/packages.js:3608:210)
    at Object.unmountChildren (https://XYZ/keystone/js/packages.js:2962:3)
    at h.unmountChildren (https://XYZ/keystone/js/packages.js:3544:3)
    at h.unmountComponent (https://XYZ/keystone/js/packages.js:3236:57)
    at Object.unmountComponent (https://XYZ/keystone/js/packages.js:3608:210)
    at p.unmountComponent (https://XYZ/keystone/js/packages.js:3088:29)
```

On a second click the correct behavior is restored -> view of clicked menu item is opened.

**Comment by Noviny** [comment]
Hi @xenuric, just looking to reproduce this and wasn't able to, but don't know if I followed the instructions right. Do you have example models so I can run through this in a place you are encountering this error?

**Comment by xenurec** [comment]
It's very strange, sorry for my complicated instructions. But I think this bug still exists. Now a little bit different instuction to reproduce:

1. Open Comments list (http://demo.keystonejs.com/keystone/post-comments)
2. Click on one of the referenced Authors (so you get to the User detail page)
3. Use back button of your browser, so you're now back at Comments list
4. Repeat 2. and 3.!
5. Repeat 2. and 3.!
6. After third time clicking on an Author you get a mixed-up form and some console errors.
7. Using back button of browser changes url but view doesn't change.

I hope this will help you. Let me know if so, otherwise I can upload some screenshots or screencast.

**Comment by callumflack** [comment]
I'm having this same problem. Will report back with specifics later this week, when I have time.

**Comment by Noviny** [comment]
Just an update on where we are at. We've verified the issue (thanks @xenurec for the help with the steps), but haven't figured out why this occurs yet, or how to prevent it. @callumflack if you end up finding more details, that would be great.

**Comment by callumflack** [comment]
@Noviny @xenurec we were on keystone 4.0.0-beta.1 and in admin, user records were not loading and also not updating when they did load. Same error as @xenurec : `fields.js:9421 Uncaught TypeError: values.split is not a function`.

This morning I updated to keystone 4.0.0-beta.5 and tried replicating steps that 10mins prior would fail with `values.split is not a function` error and all worked…

That's pretty unscientific, but it's all I have time for right now. We'll keep watching things here and if it reoccurs, we'll try to be specific. My intuition is the issue is still there in some form 🗡

**Comment by larrybolt** [comment]
I had the same behavior when trying to populate a field using populate in my model. It's expecting an array or string with ids, but get's an array with objects instead.
``` js
User.schema.pre('findOne', function () {
	this.populate('customer');
});
```
probably not the cause it's acting up for other people, but it might help
